spring:
  application:
    name: TPConceptionSI

  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/dev-db

  jpa:
    hibernate:
      ddl-auto: create-drop


logging:
  level:
    org.hibernate: warn
    com.zaxxer.hikari: warn
    org.hibernate.engine.transaction.jta.platform.internal: error